db:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=rush_db
        - MYSQL_USER=rush
        - MYSQL_PASSWORD=rush

rush:
    build: .
    dockerfile: rush/rush.Dockerfile
    links:
        - "db:db"
    ports:
        - "8000:8000"
    volumes:
        - "./:/home/app/rush"
