# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _0005_auto_20160305_1951_forwards_func(apps, schema_editor):
    """
    Create user groups: Moderators, Administrators, Individual contestants.
    """
    Group.objects.bulk_create([
        Group(name='Moderators'),
        Group(name='Administrators'),
        Group(name='Individual contestants')
    ])


def _0005_auto_20160305_1951_backwards_func(apps, schema_editor):
    """
    Delete user groups: Moderators, Administrators, Individual contestants.
    """
    Group.objects.filter(
        Q(name='Moderators') |
        Q(name='Administrators') |
        Q(name='Individual contestants')
    ).delete()


class Migration(migrations.Migration):

    replaces = [(b'contest', '0001_initial'), (b'contest', '0002_contestant'), (b'contest', '0003_auto_20160214_1700'), (b'contest', '0004_auto_20160223_2144'), (b'contest', '0005_auto_20160305_1951'), (b'contest', '0006_auto_20160404_2121'), (b'contest', '0007_auto_20160414_2144'), (b'contest', '0008_auto_20160508_1853'), (b'contest', '0009_auto_20160508_2022'), (b'contest', '0010_auto_20160512_2214')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='RushUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='nazwa u\u017cytkownika')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adres email')),
                ('first_name', models.CharField(max_length=32, verbose_name='imi\u0119')),
                ('last_name', models.CharField(max_length=32, verbose_name='nazwisko')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='nazwa organizacji')),
                ('organization_address', models.CharField(max_length=255, verbose_name='adres organizacji')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data do\u0142\u0105czenia')),
                ('is_active', models.BooleanField(default=False, verbose_name='u\u017cytkownik zaakceptowany')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='imi\u0119')),
                ('last_name', models.CharField(max_length=32, verbose_name='nazwisko')),
                ('gender', models.CharField(choices=[(None, 'Wybierz p\u0142e\u0107'), ('F', 'Kobieta'), ('M', 'M\u0119\u017cczyzna')], max_length=1, verbose_name='p\u0142e\u0107')),
                ('age', models.IntegerField(verbose_name='wiek')),
                ('school', models.CharField(max_length=255, verbose_name='rodzaj szko\u0142y')),
                ('styles_distances', models.CharField(max_length=255, verbose_name='style i dystanse')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa klubu')),
                ('code', models.IntegerField(default=0, verbose_name='kod klubu')),
            ],
        ),
        migrations.AddField(
            model_name='rushuser',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Club'),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('age_min', models.SmallIntegerField()),
                ('age_max', models.SmallIntegerField()),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.Club')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Organizer'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=_0005_auto_20160305_1951_forwards_func,
            reverse_code=_0005_auto_20160305_1951_backwards_func,
        ),
        migrations.AddField(
            model_name='rushuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to=b'auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='rushuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='rushuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to=b'auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='adres email')),
                ('website', models.URLField(blank=True, verbose_name='strona internetowa')),
                ('phone_number', models.CharField(blank=True, max_length=9, verbose_name='numer telefonu')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa szko\u0142y')),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='rushuser',
            name='club',
        ),
        migrations.AddField(
            model_name='contest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='contest',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rushuser',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rushuser',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contact'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='school',
            field=models.CharField(choices=[(None, 'Wybierz rodzaj szko\u0142y'), ('P', 'Szko\u0142a podstawowa'), ('G', 'Gimnazjum'), ('S', 'Szko\u0142a \u015brednia')], max_length=1, verbose_name='rodzaj szko\u0142y'),
        ),
        migrations.AlterField(
            model_name='rushuser',
            name='organization_address',
            field=models.CharField(max_length=255, verbose_name='Adres Szko\u0142y/Klubu'),
        ),
        migrations.AlterField(
            model_name='rushuser',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Nazwa Szko\u0142y/Klubu'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='age_max',
            field=models.SmallIntegerField(verbose_name='Wiek maksymalny'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='age_min',
            field=models.SmallIntegerField(verbose_name='Wiek minimalny'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='deadline',
            field=models.DateTimeField(verbose_name='Termin zg\u0142aszania zawodnik\xf3w'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Miejsce'),
        ),
    ]
