# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RushUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='nazwa u\u017cytkownika')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adres email')),
                ('first_name', models.CharField(max_length=32, verbose_name='imi\u0119')),
                ('last_name', models.CharField(max_length=32, verbose_name='nazwisko')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='nazwa organizacji')),
                ('organization_address', models.CharField(max_length=255, verbose_name='adres organizacji')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data do\u0142\u0105czenia')),
                ('is_active', models.BooleanField(default=False, verbose_name='u\u017cytkownik zaakceptowany')),
                ('is_admin', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa klubu')),
                ('code', models.IntegerField(default=0, verbose_name='kod klubu')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adres email')),
                ('website', models.URLField(blank=True, verbose_name='strona internetowa')),
                ('phone_number', models.CharField(blank=True, max_length=9, verbose_name='numer telefonu')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=255)),
                ('age_min', models.SmallIntegerField()),
                ('age_max', models.SmallIntegerField()),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='imi\u0119')),
                ('last_name', models.CharField(max_length=32, verbose_name='nazwisko')),
                ('gender', models.CharField(choices=[(None, 'Wybierz p\u0142e\u0107'), ('F', 'Kobieta'), ('M', 'M\u0119\u017cczyzna')], max_length=1, verbose_name='p\u0142e\u0107')),
                ('age', models.IntegerField(verbose_name='wiek')),
                ('school', models.CharField(max_length=255, verbose_name='rodzaj szko\u0142y')),
                ('styles_distances', models.CharField(max_length=255, verbose_name='style i dystanse')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.Club')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa szko\u0142y')),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest.Contact'),
        ),
    ]
