# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RushUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adres email')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='imie')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='nazwisko')),
                ('organization_name', models.CharField(max_length=30, null=True, verbose_name='nazwa organizacji')),
                ('organization_address', models.CharField(max_length=30, null=True, verbose_name='adres organizacji')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
