# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushuser',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
