# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_squashed_0010_auto_20160512_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nazwa zawod\xf3w'),
            preserve_default=False,
        ),
    ]
