# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='imi\u0119')),
                ('last_name', models.CharField(max_length=32, verbose_name='nazwisko')),
                ('gender', models.CharField(choices=[('F', 'Kobieta'), ('M', 'M\u0119\u017cczyzna')], max_length=2, verbose_name='p\u0142e\u0107')),
                ('age', models.IntegerField(verbose_name='wiek')),
                ('school', models.CharField(max_length=254, verbose_name='szko\u0142a')),
                ('styles_distances', models.CharField(max_length=254, verbose_name='styl i dystans')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
