# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushuser',
            name='club',
            field=models.ForeignKey(blank=True, default=34343, on_delete=django.db.models.deletion.CASCADE, to='contest.Club'),
            preserve_default=False,
        ),
    ]
