# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushuser',
            name='organization_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres Szko\u0142y/Klubu'),
        ),
        migrations.AlterField(
            model_name='rushuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa Szko\u0142y/Klubu'),
        ),
    ]
