# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20160127_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
        migrations.AddField(
            model_name='club',
            name='code',
            field=models.IntegerField(default=0, verbose_name='kod klubu'),
        ),
    ]
