# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_rushuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushuser',
            name='username',
        ),
    ]
