# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 00:43
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D25', 'Dowolny 25m'), ('D50', 'Dowolny 50m'), ('D100', 'Dowolny 100m'), ('D200', 'Dowolny 200m'), ('D400', 'Dowolny 400m'), ('D800', 'Dowolny 800m'), ('D1500', 'Dowolny 1500m'), ('G25', 'Grzbietowy 25m'), ('G50', 'Grzbietowy 50m'), ('G100', 'Grzbietowy 100m'), ('G200', 'Grzbietowy 200m'), ('K25', 'Klasyczny 25m'), ('K50', 'Klasyczny 50m'), ('K100', 'Klasyczny 100m'), ('K200', 'Klasyczny 200m'), ('M25', 'Motylkowy 25m'), ('M50', 'Motylkowy 50m'), ('M100', 'Motylkowy 100m'), ('M200', 'Motylkowy 200m'), ('Z100', 'Zmienny 100m'), ('Z200', 'Zmienny 200m')], default='D25', max_length=97),
            preserve_default=False,
        ),
    ]
