# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20160725_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('docfile1', models.FileField(default='brak', upload_to='trolollo/', verbose_name='Plik1')),
                ('docfile2', models.FileField(default='brak', upload_to='trolollo/', verbose_name='Plik2')),
                ('docfile3', models.FileField(default='brak', upload_to='trolollo/', verbose_name='Plik3')),
                ('docfile4', models.FileField(default='brak', upload_to='trolollo/', verbose_name='Plik4')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
