# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20160725_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='age',
        ),
        migrations.AddField(
            model_name='contest',
            name='highest_year',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Rocznik maksymalny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='lowest_year',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Rocznik minimalny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestant',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Rocznik'),
            preserve_default=False,
        ),
    ]
