# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contest_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='results',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Wyniki'),
        ),
    ]
