# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 17:17
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.db import migrations
from django.db.models import Q


def forwards_func(apps, schema_editor):
    """
    Create user groups: Moderators, Administrators, Individual contestants.
    """
    Group.objects.bulk_create([
        Group(name='Moderators'),
        Group(name='Administrators'),
        Group(name='Individual contestants')
    ])


def backwards_func(apps, schema_editor):
    """
    Delete user groups: Moderators, Administrators, Individual contestants.
    """
    Group.objects.filter(
        Q(name='Moderators') |
        Q(name='Administrators') |
        Q(name='Individual contestants')
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20160223_2144'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
