# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20160223_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushuser',
            name='has_setted_password',
            field=models.BooleanField(default=False),
        ),
    ]
