# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 17:17
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group


def forwards_func(apps, schema_editor):
    """
    Create user groups: Moderators, Administrators, Individual contestants
    """
    Group.objects.get_or_create(name='Moderators')
    Group.objects.get_or_create(name='Administrators')
    Group.objects.get_or_create(name='Individual contestants')


def backwards_func(apps, schema_editor):
    """
    Delete user groups: Moderators, Administrators, Individual contestants
    """
    Group.objects.filter(name='Moderators').delete()
    Group.objects.filter(name='Administrators').delete()
    Group.objects.filter(name='Individual contestants').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20160223_2144'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
