# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contest', '0005_auto_20160305_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='rushuser',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='contest',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
