# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20160801_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestfiles',
            name='docfile',
        ),
        migrations.AddField(
            model_name='contestfiles',
            name='file',
            field=models.FileField(default='', upload_to=b'', verbose_name='Pliki'),
        ),
    ]
