# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushuser',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
