# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20160305_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushuser',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
