# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_rushuser_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushuser',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='powiadomienia'),
        ),
    ]
