# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contestfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestfiles',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nazwa pliku'),
        ),
    ]
