# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20160318_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adres email')),
                ('website', models.URLField(blank=True, verbose_name='strona internetowa szko\u0142y/klubu')),
                ('phone_number', models.CharField(blank=True, max_length=9, verbose_name='numer telefonu')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa szko\u0142y')),
            ],
        ),
        migrations.AddField(
            model_name='rushuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.School'),
        ),
    ]
