# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20160322_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contact'),
        ),
    ]
