# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contest', '0006_auto_20160404_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='adres email')),
                ('website', models.URLField(blank=True, verbose_name='strona internetowa')),
                ('phone_number', models.CharField(blank=True, max_length=9, verbose_name='numer telefonu')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa szko\u0142y')),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='rushuser',
            name='club',
        ),
        migrations.AddField(
            model_name='contest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='contest',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rushuser',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rushuser',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contact'),
        ),
    ]
