# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 13:53
from __future__ import unicode_literals

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20160803_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestfiles',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='contestfiles',
            name='file',
            field=models.FileField(default='', upload_to=contest.models.contest_directory_path, verbose_name='Pliki'),
        ),
    ]
