# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20160319_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='rushuser',
            name='club',
        ),
        migrations.RemoveField(
            model_name='rushuser',
            name='school',
        ),
    ]
