# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20160130_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='code',
            field=models.IntegerField(default=0, verbose_name='kod klubu'),
        ),
    ]
