# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20160414_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='age_max',
            field=models.SmallIntegerField(verbose_name='Wiek maksymalny'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='age_min',
            field=models.SmallIntegerField(verbose_name='Wiek minimalny'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='deadline',
            field=models.DateTimeField(verbose_name='Czas do ko\u0144ca dodawania zg\u0142osze\u0144'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Miejsce'),
        ),
    ]
