# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20160815_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushuser',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='powiadomienia'),
        ),
    ]
