# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20160414_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='school',
            field=models.CharField(choices=[(None, 'Wybierz rodzaj szko\u0142y'), ('P', 'Szko\u0142a podstawowa'), ('G', 'Gimnazjum'), ('S', 'Szko\u0142a \u015brednia')], max_length=1, verbose_name='rodzaj szko\u0142y'),
        ),
    ]
