# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20160815_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_result', models.TimeField(blank=True, null=True, verbose_name='Najlepszy czas')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contestant')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16, verbose_name='Dystans')),
            ],
        ),
        migrations.CreateModel(
            name='RoundStyleDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Distance')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa stylu')),
            ],
        ),
        migrations.AddField(
            model_name='roundstyledistance',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Style'),
        ),
        migrations.AddField(
            model_name='contestantscore',
            name='style_distance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.RoundStyleDistance'),
        ),
        migrations.AlterUniqueTogether(
            name='contestantscore',
            unique_together=set([('contestant', 'style_distance')]),
        ),
    ]
