# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20160131_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(default=1, max_length=254, verbose_name='nazwa klubu'),
            preserve_default=False,
        ),
    ]
