# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_rushuser_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushuser',
            name='notifications',
        ),
        migrations.AddField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
