# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20160319_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushuser',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='rushuser',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
