# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20160508_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushuser',
            name='organization_address',
            field=models.CharField(max_length=255, verbose_name='Adres Szko\u0142y/Klubu'),
        ),
        migrations.AlterField(
            model_name='rushuser',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Nazwa Szko\u0142y/Klubu'),
        ),
    ]
