# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_rushuser_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='organization',
            field=models.CharField(default='', max_length=255, verbose_name='Organizacja'),
        ),
    ]
