# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20160505_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='deadline',
            field=models.DateTimeField(verbose_name='Termin zg\u0142aszania zawodnik\xf3w'),
        ),
    ]
