# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='code',
            field=models.CharField(default=0, max_length=5, verbose_name='kod klubu'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, max_length=254, verbose_name='nazwa klubu'),
        ),
        migrations.AlterField(
            model_name='rushuser',
            name='club',
            field=models.ForeignKey(default=33333, on_delete=django.db.models.deletion.CASCADE, to='contest.Club'),
            preserve_default=False,
        ),
    ]
