# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 22:59
from __future__ import unicode_literals

import contest.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20161001_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushuser',
            name='first_name',
            field=models.CharField(max_length=32, validators=[contest.validators.LettersValidator()], verbose_name='imi\u0119'),
        ),
        migrations.AlterField(
            model_name='rushuser',
            name='last_name',
            field=models.CharField(max_length=32, validators=[contest.validators.LettersValidator()], verbose_name='nazwisko'),
        ),
    ]
